### ISSUE TITLE
Can't get any password

### ISSUE THREAD

**Issue by odelucca** [yardnsm/tmux-1password#14] opened 2020-01-16 22:37 UTC
I'm trying to get this plugin to work. I've installed it with `tpm` and have checked that I've already `fzf` and `jq` installed. Also, I have the `op` cli tool installed and configured (I use it on my shell)

But, everytime I type `prefix + u` I can't see any password (only an empty list). Also, every time I use the command I need to login again.

Can anyone help me?

**Comment by yardnsm** [comment] 2020-01-20 06:25
Thanks for reporting! This is probably a duplicate of #1, and I also noticed that you tried #13 and it worked fine (I'm hoping to merge it soon!) 😁

Closing.

**Closed by yardnsm** 2020-01-20 06:25 UTC
